### ISSUE TITLE
The result is not convincing!

### ISSUE THREAD

**Issue by adignatov** [IsaacChanghau/StockPrediction#1]
Hi!

I tested your app and got accuracy of prediction is about 50%.
So... not good :)

**Comment by IsaacChanghau** [comment]
Oh, I'm sorry, but it is just a plain version of stock price prediction, I create it just for practice, not really expect it can give good results for all requirements. But the data I test in the resources folder seems OK. So you use you own data? if the result is not good, I guess it is better to change some hyper parameters, and also, this app I got some good result in Open, Close, Low, High prices, not  for Volume.

**Comment by IsaacChanghau** [comment]
Here is the training information and the predicted graph I did just now for your reference. And I see the dataset I have again, maybe for some of them, you can not get really good results, since here are few data of the stock available in the dataset.

[main] INFO com.isaac.stock.predict.StockPricePrediction - Create dataSet iterator...
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.reflections.Reflections - Reflections took 688 ms to scan 265 urls, producing 137957 keys and 152985 values 
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 2
[main] INFO org.reflections.Reflections - Reflections took 142 ms to scan 10 urls, producing 31 keys and 227 values 
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1.8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
[main] INFO org.reflections.Reflections - Reflections took 210 ms to scan 10 urls, producing 387 keys and 1538 values 
[main] INFO com.isaac.stock.predict.StockPricePrediction - Load test dataset...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Build lstm networks...
[main] INFO org.reflections.Reflections - Reflections took 6530 ms to scan 244 urls, producing 5981 keys and 37937 values 
[main] INFO org.deeplearning4j.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
[main] INFO com.isaac.stock.predict.StockPricePrediction - Training...
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 0 is 0.23434746144095608
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 100 is 0.20113913935428646
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 200 is 0.05824922895164289
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 300 is 0.051438126356106124
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 400 is 0.03307240534001015
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 500 is 0.005602465211583573
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 600 is 0.00763037185169556
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 700 is 0.006922101665681733
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 800 is 0.23132369174702785
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 900 is 0.004381681707088254
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1000 is 0.004832698348680974
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1100 is 0.22094475341984313
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1200 is 0.009119874427888187
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1300 is 0.04864256246640972
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1400 is 0.010901873210011521
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1500 is 0.006273117646453835
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1600 is 0.01347278043972134
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1700 is 0.006186692240985793
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1800 is 0.04128379029296486
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1900 is 0.018139030591768825
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2000 is 0.005515170787791811
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2100 is 0.0780544865359251
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2200 is 0.013574863339994503
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2300 is 0.010617894996399469
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2400 is 0.016081307244125473
[main] INFO com.isaac.stock.predict.StockPricePrediction - Saving model...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Load model...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Testing...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Print out Predictions and Actual Values...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Predict,Actual
[main] INFO com.isaac.stock.predict.StockPricePrediction - 714.5552878535982,720.0900268554688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 726.3188345154078,725.27001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 733.1107499445152,724.1199951171875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 732.9060256887477,732.6599731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 738.3539498204508,735.719970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 743.4407650853276,734.1500244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 742.9337493408655,730.4000244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 739.3375070880967,722.3400268554688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 734.6764429776064,716.5499877929688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 729.8207061318869,716.6500244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 729.1092502735808,728.280029296875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 736.01272692534,728.5800170898438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 736.6948451300611,719.4099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 731.5339043409327,718.3599853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 731.1084018107292,718.27001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 729.7195871249179,718.9199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 731.7715180243268,710.3599853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 723.4886744057075,691.719970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 710.7584414029504,693.7100219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 709.562061834722,695.9400024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 709.9357084639157,697.4600219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 710.6563278992496,701.8699951171875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 710.5449797830403,675.219970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 691.4121768216344,668.260009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 681.2113752204614,680.0399780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 690.3747036240345,684.1099853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 696.0221309036635,692.0999755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 701.214966623687,699.2100219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 708.9598585459406,694.9500122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 706.77853651819,697.77001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 708.521178934042,695.3599853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 707.9635859272253,705.6300048828125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 715.6662117383818,715.0900268554688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 725.2009491535024,720.6400146484375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 732.4949433611538,716.97998046875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 732.7709517219394,720.9500122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 734.1720555459352,719.8499755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 735.5198472415641,733.780029296875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 742.5355244353027,736.9600219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 746.4665569092484,741.1900024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 752.0453639143906,738.6300048828125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 751.2134318805877,742.739990234375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 753.4866383027987,739.77001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 752.3957109058704,738.4199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 750.8980343456789,741.77001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 753.0438741507522,745.9099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 756.3596683251832,768.7899780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.2611166513453,772.8800048828125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 777.2371026959046,771.0700073242188
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.9121903694822,773.1799926757812
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.6102540581917,771.6099853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.8826060731735,782.219970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 786.2879819333155,781.760009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 788.4797816944892,784.260009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 791.6132633073564,784.6799926757812
[main] INFO com.isaac.stock.predict.StockPricePrediction - 792.4202263696455,784.8499755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 793.802328202518,783.219970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 791.1451394886516,782.4400024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 792.347983285636,777.1400146484375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.3543310538748,779.9099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 788.0274277525299,777.5
[main] INFO com.isaac.stock.predict.StockPricePrediction - 788.8599991056602,775.4199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 785.6360538079493,772.1500244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 783.14274394837,772.0800170898438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 784.2284502374571,769.6400146484375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 781.2111826712365,769.4099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.1947695122451,769.5399780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 780.9871722824223,772.1500244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 781.6171149264699,769.0900268554688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 780.7506951667216,767.0499877929688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.1724268720633,768.780029296875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.1291682456937,771.4600219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 782.0827880210859,780.0800170898438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.0384717883406,780.3499755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 789.2452600359705,775.3200073242188
[main] INFO com.isaac.stock.predict.StockPricePrediction - 786.6341023136855,759.6599731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 775.7203886268493,769.02001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 774.4863247360377,759.6900024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 771.8345347187148,762.489990234375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 773.2798936472711,771.760009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.0552538464253,768.8800048828125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 777.9926715878095,765.7000122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.2575984135848,771.4099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 780.756093863265,776.219970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 783.5575201209675,787.2100219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 792.9728113750635,786.9000244140625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 794.7060771074453,774.2100219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 786.7192383374667,783.010009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 789.6674949340558,781.5599975585938
[main] INFO com.isaac.stock.predict.StockPricePrediction - 788.5155125413494,775.010009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.8722152269047,777.2899780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 786.7620016969296,772.5599975585938
[main] INFO com.isaac.stock.predict.StockPricePrediction - 782.7417486590547,776.4299926757812
[main] INFO com.isaac.stock.predict.StockPricePrediction - 785.6238357052456,776.469970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.2663891286007,776.8599853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.0940215343538,775.0800170898438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 785.5493550035898,785.9400024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 792.0615327091676,783.0700073242188
[main] INFO com.isaac.stock.predict.StockPricePrediction - 793.8749264639316,786.1400146484375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 794.1585001034263,778.1900024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 787.8407465088947,778.530029296875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 789.4270043136878,779.9600219726562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 790.3557932256095,795.260009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 801.1714424311526,801.5
[main] INFO com.isaac.stock.predict.StockPricePrediction - 807.2790730733733,796.969970703125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 806.0697650476329,799.3699951171875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 804.4727808852336,813.1099853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 815.6603008329497,807.6699829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 815.5469282055365,799.0700073242188
[main] INFO com.isaac.stock.predict.StockPricePrediction - 808.0904048177339,795.3499755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 804.2958315024729,795.3699951171875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 807.3521330654124,784.5399780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 795.392244334574,783.6099853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 790.2323335599177,768.7000122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.8305725834616,762.1300048828125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 772.8892340204172,762.02001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 768.376563029392,782.52001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 786.4499073118795,790.510009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 793.8265868192232,785.3099975585938
[main] INFO com.isaac.stock.predict.StockPricePrediction - 789.3649548211781,762.5599975585938
[main] INFO com.isaac.stock.predict.StockPricePrediction - 778.7999898275028,754.02001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 764.0015232824851,736.0800170898438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 751.8576526562832,758.489990234375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 763.7326539875235,764.47998046875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 767.6008910964107,771.22998046875
[main] INFO com.isaac.stock.predict.StockPricePrediction - 776.7491244603063,760.5399780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 773.7904966835154,769.2000122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 775.1223053959563,768.27001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 779.4431805887262,760.989990234375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 772.0040253759879,761.6799926757812
[main] INFO com.isaac.stock.predict.StockPricePrediction - 772.982503606754,768.239990234375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 777.5273891883381,770.8400268554688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 781.3171676086428,758.0399780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 772.6832666437352,747.9199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 760.3037358098621,750.5
[main] INFO com.isaac.stock.predict.StockPricePrediction - 759.2577738723026,762.52001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 769.3442793848116,759.1099853515625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 771.2910422548439,771.1900024414062
[main] INFO com.isaac.stock.predict.StockPricePrediction - 775.0704139772062,776.4199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 782.2967113716214,789.2899780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - 792.5194274186321,789.27001953125
[main] INFO com.isaac.stock.predict.StockPricePrediction - 794.724759438905,796.0999755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 803.0057561350227,797.0700073242188
[main] INFO com.isaac.stock.predict.StockPricePrediction - 803.7761359246817,797.8499755859375
[main] INFO com.isaac.stock.predict.StockPricePrediction - 803.9837015996825,790.7999877929688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 801.1456565516095,794.2000122070312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 799.2695029495275,796.4199829101562
[main] INFO com.isaac.stock.predict.StockPricePrediction - 802.9124865486859,794.5599975585938
[main] INFO com.isaac.stock.predict.StockPricePrediction - 800.486553842679,791.260009765625
[main] INFO com.isaac.stock.predict.StockPricePrediction - 798.9946666741756,789.9099731445312
[main] INFO com.isaac.stock.predict.StockPricePrediction - 798.2066700852694,791.5499877929688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 800.1763418978711,785.0499877929688
[main] INFO com.isaac.stock.predict.StockPricePrediction - 796.88945916414,782.7899780273438
[main] INFO com.isaac.stock.predict.StockPricePrediction - Plot...
[main] INFO com.isaac.stock.predict.StockPricePrediction - Done...
<img width="680" alt="1" src="https://user-images.githubusercontent.com/20762516/33648670-ecd0840a-da95-11e7-90b8-0d414d9793a7.png">

**Comment by adignatov** [comment]
To understand if prediction works or not, you need to compare last test value with predicted value and real value. If direction of real and predicted values will be the same, prediction correct. Am I right?

**Comment by sanchita1992** [comment]
Does this program predict the price of the next day?

**Comment by leodennis** [comment]
I agree, 
he is predicting only one day ahead at a time, because he is not taking the prediction as input for the next prediciton, but the actual value.

This results in a lag of the actual signal, all your network has to do is produce a similar value to the last input of the price.

If you would take your prediction as the input for the next prediction you would see that the results are quite bad!

Still if changed correctly you can use this example for actual predictions, but maybe not stocks because they won't be good...

**Comment by leodennis** [comment]
This is what is happening if you take predicted values as input for the next prediction:
![real](https://user-images.githubusercontent.com/26283266/40243286-17f86562-5ac0-11e8-9b16-90ab708ca9c0.PNG)

**Comment by rajekra** [comment]
I built the file and unable to run the jar. Can some one help me? Getting below error.

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
        at sun.security.util.SignatureFileVerifier.process(Unknown Source)
        at java.util.jar.JarVerifier.processEntry(Unknown Source)
        at java.util.jar.JarVerifier.update(Unknown Source)
        at java.util.jar.JarFile.initializeVerifier(Unknown Source)
        at java.util.jar.JarFile.getInputStream(Unknown Source)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
        at sun.misc.Resource.cachedInputStream(Unknown Source)
        at sun.misc.Resource.getByteBuffer(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
